TimeClock/urls.py
from django.urls import path, re_path
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from . views import EditJobCode,EditMachine,EditTimecard,JobCodeView,MachineView,TimecardView,JobCodeDelete,MachineDelete,JobCodeAdd,MachineAdd,TimecardAdd,TimecardAdd2
from . models import JobCode,Machine,Timecard
from django.views.generic.edit import DeleteView
from django.views.generic import TemplateView
from . import views

app_name='TimeClock'
urlpatterns = [
    path('jobcode/',JobCodeView.as_view(),name='Jobcode'),
    path('machine/',MachineView.as_view(),name='Machine'),
    path('timecard/',TimecardView.as_view(),name='Timecard'),
    path('edit/jobcode/<int:pk>',EditJobCode.as_view(),name='jobCodeEdit'),
    path('edit/machine/<int:pk>',EditMachine.as_view(),name='machineEdit'),
    path('edit/timecard/<int:pk>',EditTimecard.as_view(),name='timecardEdit'),
    path('delete/jobcode/<int:pk>',JobCodeDelete.as_view(),name='jobCodeDelete'),
    path('delete/machine/<int:pk>',MachineDelete.as_view(),name='machineDelete'),
    path('delete/timecard/<int:pk>',DeleteView.as_view(),name='timecardDelete'),
    path('add/jobcode/', JobCodeAdd.as_view(),name='jobCodeAdd'),
    path('add/machine/', MachineAdd.as_view(),name='machineAdd'),
    path('add/timecard/',TimecardAdd2.as_view(),  name='timecardAdd'),
    #path('modelform/', views.modelformview, name='addmodalform'),
    #path('insert/', views.insert, name='insert'),
    path('register/', views.register, name='register')
]

TimeClock/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class JobCode(models.Model):
    jobCode = models.TextField()
    description = models.TextField()
    hourlyRate = models.IntegerField()
    maxHoursPerDay = models.IntegerField()
    objects = models.Manager()

    def __unicode__(self):
        return u'%s' % self.jobCode

    def get_absolute_url(self):
        return reverse('TimeClock:Jobcode')

class Machine(models.Model):
    machineCode = models.TextField()
    description = models.TextField()
    hourlyRent = models.IntegerField()
    maxHoursPerDay = models.IntegerField()
    objects = models.Manager()
    
    def __unicode__(self):
        return u'%s' % self.machineCode

    def get_absolute_url(self):
        return reverse('TimeClock:Machine')

class Timecard(models.Model):
    siteCode = models.TextField()
    contractorName = models.TextField()
    totalHours = models.IntegerField()
    totalAmount = models.IntegerField()
    objects = models.Manager()

    def __unicode__(self):
        return u'%s' % self.siteCode

    def get_absolute_url(self):
        return reverse('TimeClock:Timecard')

TimeClock/templates/index.html
<!DOCTYPE html>
<html lang="en">
<style type='text/css'>
    html,body {
        height:100%;
        margin:0px;
    }
    .container1{
        height: 100%;
        }
</style>
{% load staticfiles %}
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-11/css/all.min.css">
<title>DR: Disaster Recovery Application</title>
</head>
<body>
    <div class="row">
        <div class="col-sm-12 text-dark mt-1" style="font-size:x-large;background:gray;">Disaster Recovery Application: Timecard Submission {% if user.username %} <p style='float:right'><a class='text-dark' href="/logout?next=/">{{user.username}}</a></p> {% else %} <a href='/login' class='text-dark' style="float:right;">login</a> <a href='/timeclock/register' class='text-dark' style="float:right;">Sign up</a> {% endif %} </div>
    </div>
    <div class="row container1">
        <div class="col-lg-3" style='background:lightgray'>
            {% if user.username %}
            {% if perms.auth.Admin %}
            <div class='mt-5 ml-5'><a class='text-dark' href="{% url 'TimeClock:Jobcode' %}">Job code Management</a><br/></div>
            <div class='mt-3 ml-5'><a class='text-dark' href="{% url 'TimeClock:Machine' %}">Machine Management</a><br/></div>
            <div class='mt-5 ml-5'><a class='text-dark' href="{% url 'TimeClock:Timecard' %}">Timecard Approval</a><br/></div>
            {% elif perms.auth.Contractor %}
            <div class='mt-5 ml-5'><a class='text-dark' href="{% url 'TimeClock:Timecard' %}">Timecard Approval</a><br/></div>
            {% endif %}
            {% else %} {% endif %}
        </div>
        <div class="col-lg-9">
            <div class="row mt-3 mb-5" style='font-size:x-large;background:lightgray;'>{% block title %} {% endblock %}</div>
            <div class="row mt-5 mx-1" style='width:100%;height: 100%' >{% block content %}{% endblock %}</div><div id = 'test'></div>
        </div>
    </div>

   



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block javascript %} {% endblock %}
</body>
</html>

TimeClock/templates/job_code.html
{% extends 'index.html' %}

{% block title %}{% if user.username %}Job Code Management{% else %} Please Login {% endif %}{% endblock %}

{% block content %}
{% if perms.auth.Admin %}

<a class='text-dark' href='/timeclock/add/jobcode/' style='width:100%;padding-top:-10px;text-align:right;'>Add New</a>
<table style='width:100%;margin-top:-300px;'>


    <tr class='bg-dark text-white' style='font-size:x-large'>
        <th>Job code</th>
        <th class='bg-white'></th>
        <th>Description</th>
        <th class='bg-white'></th>
        <th>Hourly Rate</th>
        <th class='bg-white'></th>
        <th>Max Hours per day</th>
        <th class='bg-white'></th>
        <th class='text-dark'></th>
        <th class='bg-white'></th>
        <th class='text-dark'>delete</th>
        <th class='bg-white'></th>
    </tr>
    {% for JobCode in object_list %}
    <tr><td class='bg-white'></td></tr>
    <tr style='color:black;background:lightgray'>
        <td class='py-2'>{{JobCode.jobCode}}</td>
        <td class='bg-white'></td>
        <td>{{JobCode.description}}</td>
        <td class='bg-white'></td>
        <td>${{JobCode.hourlyRate}}/Hr.</td>
        <td class='bg-white'></td>
        <td>{{JobCode.maxHoursPerDay}} Hr.</td>
        <td class='bg-white'></td>
        <td><a class='text-dark' href='/timeclock/edit/jobcode/{{JobCode.id}}'>Edit</a></td>
        <td class='bg-white'></td>
        <td><form method="POST" action="{% url 'TimeClock:jobCodeDelete' JobCode.id %}">{% csrf_token %}<input style='background:none;border:0;' onclick="return confirm('Did you mean to delete {{JobCode.jobCode}}?')" type="submit" value="Delete"/></form></td>
    </tr>
    
    {% endfor %}


</table>
{% endif %}
{% endblock %}

TimeClock/templates/job_code_add.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Add A Job Code{% else %} Please Login {% endif %} {% endblock %}

{% block content %}
{% if perms.auth.Admin %}
    <form class='text-dark' method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type='submit' value='submit'/>
    </form>
{% endif %}
{% endblock %}

TimeClock/templates/job_code_edit.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Edit A Job Code{% else %} Please Login {% endif %}{% endblock %}
{% block content %}
{% if perms.auth.Admin %}
    <form method='post' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='submit'/>
    </form>
{% endif %}
{% endblock %}

TimeClock/templates/login.html
{% extends 'index.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <form method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="Submit" value='login'></input>
    </form>

{% endblock %}

TimeClock/templates/machine.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Machine Management{% else %} Please Login {% endif %}{% endblock %}

{% block content %}
{% if perms.auth.Admin %}
<a class='text-dark' href='/timeclock/add/machine' style='width:100%;padding-top:-10px;text-align:right;'>Add New</a>


<table style='width:100%;margin-top:-300px;'>
    <tr class='bg-dark text-white' style='font-size:x-large'>
        <th>Machine code</th>
        <th class='bg-white'></th>
        <th>Description</th>
        <th class='bg-white'></th>
        <th>Hourly Rent</th>
        <th class='bg-white'></th>
        <th>Max Hours per day</th>
        <th class='bg-white'></th>
        <th class='text-dark'>edit</th>
        <th class='bg-white'></th>
        <th class='text-dark'>delete</th>
        <th class='bg-white'></th>
    </tr>
    {% for Machine in object_list %}
    <tr><td class='bg-white'></td></tr>
    <tr style='color:black;background:lightgray'>
        <td class='py-2'>{{Machine.machineCode}}</td>
        <td class='bg-white'></td>
        <td>{{Machine.description}}</td>
        <td class='bg-white'></td>
        <td>${{Machine.hourlyRent}}/Hr.</td>
        <td class='bg-white'></td>
        <td>{{Machine.maxHoursPerDay}} Hr.</td>
        <td class='bg-white'></td>
        <td><a class='text-dark' href='/timeclock/edit/machine/{{Machine.id}}'>Edit</a></td>
        <td class='bg-white'></td>
        <td><form method="POST" action="{% url 'TimeClock:machineDelete' Machine.id %}">{% csrf_token %}<input style='background:none;border:0;' onclick="return confirm('Did you mean to delete {{Machine.machineCode}}?')" type="submit" value="Delete"/></form></td>
    </tr>
    
    {% endfor %}


</table>
{% endif %}
{% endblock %}

TimeClock/templates/machine_add.html
{% extends 'index.html' %}
{% block title %}{% if user.username %} Add A Machine{% else %} Please Login {% endif %} {% endblock %}
{% block content %}
{% if perms.auth.Admin %}
    <form class='text-dark' method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type='submit' value='submit'/>
    </form>
{% endif %}
{% endblock %}

TimeClock/templates/machine_edit.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Add a Machine{% else %} Please Login {% endif %} {% endblock %}
{% block content %}
{% if perms.auth.Admin %}
    <form method='post' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='submit'/>
    </form>
{% endif %}
{% endblock %}

TimeClock/templates/modelform.html
{% extends 'index.html' %}

{% block title %} Register {% endblock %}


{% block content %}

<form action="{% url 'insert' %}" method='post'>

    {% csrf_token %}

    {{ modelform.as_p }}

    <input type="submit" value="Submit">


</form>






{% endblock %}

TimeClock/templates/register.html
{% extends 'index.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <form action=" " method="post">
        {% csrf_token %}
        Username:
        <input type="text" name="username" placeholder="Username"><br>
        Password:
        <input type="text" name="password1" placeholder="Password"><br>
        Password Confirm:
        <input type="text" name="password2" placeholder="Confirm Password"><br>
        <input type="radio" class='radio-button1' name="Admin" id="Admin"/><label for="Admin">Admin</label>
         <input type="radio" class='radio-button2' name="Contractor" id="Contractor"/><label for="Contractor">Contractor</label>





        <input type="Submit" value='login'></input>
    </form>

{% endblock %}

TimeClock/templates/timecard.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Timesheet Approval{% else %} Please Login {% endif %}{% endblock %}

{% block content %}
{% if perms.auth.Contractor %}<a class='text-dark' href='/timeclock/add/timecard/' style='width:100%;padding-top:0px;text-align:right;'>Add New</a>{% endif %}
{% if perms.auth.Contractor %}<table style='width:100%;margin-top:-300px'>{% elif perms.auth.Admin %} <table style='width:100%;margin-top:1000px'> {% endif %}
    <tr class='bg-dark text-white' style='font-size:x-large'>
        <th>Site Code</th>
        <th class='bg-white'></th>
        <th>Contractor Name</th>
        <th class='bg-white'></th>
        <th>Total Hrs</th>
        <th class='bg-white'></th>
        <th>Total Amount</th>
        <th class='bg-white'></th>
        <th class='text-dark'>Review</th>
        <th class='bg-white'></th>
    </tr>
    {% for Timecard in object_list %}
    <tr><td class='bg-white'></td></tr>
    <tr style='color:black;background:lightgray'>
        <td class='py-2'>{{Timecard.siteCode}}</td>
        <td class='bg-white'></td>
        <td>{{Timecard.contractorName}}</td>
        <td class='bg-white'></td>
        <td>{{Timecard.totalHours}} Hrs.</td>
        <td class='bg-white'></td>
        <td>${{Timecard.totalAmount}}.00</td>
        <td class='bg-white'></td>
        <td><a class='text-dark' href='/timeclock/edit/timecard/{{Timecard.id}}'>Review</a></td>
    </tr>
    
    {% endfor %}


</table>

{% endblock %}

TimeClock/templates/timecard_add.html
{% extends 'index.html' %}
{% block title %} {% if user.username %} Timesheet Submission {% else %} Please Login {% endif %} {% endblock %}

{% block javascript %} 
<script type='text/javascript'>
//generate the form to look just like the word document
//create data values for hourly cost of machines and jobcodes
//get data from form to populate timecard model
//submit button in form submits into timecard model
//OPTIONAL: auto generate total when you input code and hours
var jobcount=1,machinecount=1;

$('#jobcodeadd').on("click",function job (){
        jobcount = jobcount + 1;
        var job =`<label class=''>Labor Code : </label>
        <select id = 'machineCode'>
        {% for JobCode in JobCode %} 
        <option value = {{JobCode.id}}> 
        {{JobCode.jobCode}}  
        </option> 
        {% endfor %}
        </select>
        <label class='ml-5'>Hrs. Worked</label> 
        <input style='width:50px' type='text' id='hoursWorkedJob${jobcount}'/>
        <label class='ml-5'>Total: </label>
        <input style='width:50px' type='text' id='totalCostJob${jobcount}'/>
        <br>`
        $('#jobcodediv').append(job);
    });

$('#machineadd').on("click",function mach (){
    machinecount = machinecount + 1;
    var mach =`<label class=''>Machine Code : </label>
    <select id = 'machineCode'>
    {% for Machine in object_list %} 
    <option value ='{{Machine.id}}'>
    {{Machine.machineCode}}</option>
    {% endfor %}
    </select>
    <label class='ml-5'>Hrs. Worked</label>
    <input style='width:50px' type='text' id='hoursWorkedMachine${machinecount}'/>
    <label class='ml-5'>Total: </label>   
    <input style='width:50px' type='text' id='totalCostMachine${machinecount}'/>
    <br>`
    $('#machinecodediv').append(mach);
    });
$(document).onload(function(){
    $('document').on("click","#success",function success (){
        var site = document.getElementById('SiteCode').value;
        var contractor = document.getElementById('ContractorName').value;
        //alert(machinecount);

        //var hrtest = document.getElementById('machinecodediv').getElementById('hoursWorkedMachine2').value;
        $(document).ready(function(){
            for (var x = 1; x < machinecount;x++){
            elem1 = document.getElementById(`hoursWorkedJob${x}`).value;    
            hrs.push(elem1);
            aler(elem1)
            elem2 = document.getElementById(`totalCostJob${x}`).value;
            cost.push(elem2)
            }
            for (var x = 1; x < jobcount;x++){
            cost.push(document.getElementById(`totalCostMachine${x}`).value);
            }
            for(x in totalHrs){
            totalHrs = totalHrs + x
            }
            for(x in totalCost){
            totalCost = totalCost + x
            }


        })

        $('#machinecodediv').append(site);
        $('#machinecodediv').append(contractor);
        $('#machinecodediv').append(totalHrs);
        $('#machinecodediv').append(Cost);
    });


})


function hrs(){

};
    
    
 //   });
    
</script>
{% endblock %}
{% block content %}

{% if perms.auth.Contractor %}
<!--<div class="formContainer" style='height:100%;'>
<div class='row' id="timecardform"></div>
<br><br>

<div class = 'row' id="jobCode">
                <p>
                <label>Select list</label>
                <select id = "myList">
                  <option value = "1">one</option>
                  <option value = "2">two</option>
                  <option value = "3">three</option>
                  <option value = "4">four</option>
                </select>
                </p>
</div>
</div>
-->

<div style='height:100%;'>
    <div class="row container-fluid">
        <label>Site Code :</label> <input class='ml-3' type='text' id='SiteCode'/>
        <label class='ml-3'>Contractor Name :</label> <input class='ml-3' type='text' id='ContractorName'/>
        <label class='ml-3'>Date :</label> <input class='ml-3' type='text' id='Date'/>
    </div>
    <div class="row mt-5 ml-1 container1" style='height:30%;border:1px solid lightgray;width:1000px'>
        <div class="col-10">
        <h3 class='text-dark pl-2 ' style='margin-top:-20px;margin-left:30px;background:lightgray;height:40px;width:30%'>Labor Entry</h3>
               <div class='mt-4' style='width:100%;'>
                    <label class='ml-5'>Labor Code : </label>
                    <select id = "machineCode">
                        {% for JobCode in JobCode %}
                            <option value = "{{JobCode.id}}">
                                
                                {{JobCode.jobCode}}
                            </option>
                        {% endfor %}
                        
                    </select>
                    
                    <label class='ml-5'>Hrs. Worked</label>   <input style='width:50px' type='text' id="hoursWorkedJob1"/>
                    <label class='ml-5'>Total: </label>   <input style='width:50px' type='text' id='totalCostJob1'/>
                       
                </div>
                <div id='jobcodediv' class='ml-5'></div>
                </div>
                <div class="col-2">
                <button class='ml-5 text-primary' id="jobcodeadd" style='margin-top:250px;background:none;border:none' href='' > Add New </button>   
                </div>      
    </div>

    {% block local_content %} {% endblock %}
    <!--<div class="row mt-5 ml-1 container1" style='height:30%;border:1px solid gray;width:1000px'>
            <h3 class='text-dark pr-5 pl-2 ' style='margin-top:-20px;margin-left:30px;background:gray;height:15%'>Labor Entry</h3>
                   <div class='float-left' style='width:100%;margin-top:-100px'>
                        <label class='ml-5'>Labor Code : </label>
                        <select id = "machineCode">
                            {% for JobCode in object_list %}
                                <option value = "{{Machine.id}}">
                                    {{machineCode.value}}
                                </option>
                            {% endfor %}
                        </select>
                        
                        <label class='ml-5'>Hrs. Worked</label>   <input style='width:50px' type='text' id='hoursWorked{{JobCode.id}}'/>
                        <label class='ml-5'>Total: </label>   <input style='width:50px' type='text' id='totalCost{{JobCode.id}}'/>
                        
                    </div>
    </div>-->


<div class='float-right'><button onclick="location.reload();" class='bg-primary text-white px-5'>Clear</button> <button id="success" class='text-white px-5 bg-primary'>Submit</button> </div>


</div>





{% endif %}
{% endblock %}


TimeClock/templates/timecard_edit.html
{% extends 'index.html' %}
{% block title %}{% if user.username %}Review Timecard{% else %} Please Login {% endif %}{% endblock %}
{% block content %}
{% if perms.auth.Admin %}
    <form method='post' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type='submit' value='submit'/>
    </form>
{% endif %}
{% endblock %}

TimeClock/templates/timecard_jobcode.html
{% extends 'timecard_add.html' %}

{% block local_content %}

<div class="row mt-5 ml-1 container1" style='height:30%;border:1px solid lightgray;width:1000px'>
        <h3 class='text-dark pr-5 pl-2 ' style='margin-top:-20px;margin-left:30px;background:lightgray;height:15%'>Machine Entry</h3>
        <div class="col-10">
               <div class='float-left' style='width:100%;'>
                    <label class='ml-5'>Machine Code : </label>
                    <select id = "machineCode">
                        {% for Machine in object_list %}
                            <option value = "{{Machine.id}}">
                                {{Machine.machineCode}}
                            </option>
                        {% endfor %}
                    </select>
                    
                    <label class='ml-5'>Hrs. Worked</label>   <input style='width:50px' type='text' id='hoursWorkedMachine1'/>
                    <label class='ml-5'>Total: </label>   <input style='width:50px' type='text' id='totalCostMachine1'/>
                    
                </div>
                <div id='machinecodediv' class='ml-5'></div> 
            </div>
                    <div class="col-2">
                        <button class='ml-5 text-primary' id="machineadd" style='margin-top:200px;background:none;border:none' href='' > Add New </button>   
                    </div>    
                 
</div>

{% endblock %}